// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpBeIVAmMvTOnYOKBR9sBMZmhqq3b4STg',
    appId: '1:1098384504032:web:6c4e95627b13426ef8cc85',
    messagingSenderId: '1098384504032',
    projectId: 'homs-b9feb',
    authDomain: 'homs-b9feb.firebaseapp.com',
    storageBucket: 'homs-b9feb.firebasestorage.app',
    measurementId: 'G-ZLMS5R4KDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO-CT4PxADLAhhSePDJzEF0ssQ3owBWsU',
    appId: '1:1098384504032:android:724499c5ec3e876cf8cc85',
    messagingSenderId: '1098384504032',
    projectId: 'homs-b9feb',
    storageBucket: 'homs-b9feb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm4I8OVRulnkvS1t_iiOZyVGSzqb0KnZA',
    appId: '1:1098384504032:ios:1424ed2032770875f8cc85',
    messagingSenderId: '1098384504032',
    projectId: 'homs-b9feb',
    storageBucket: 'homs-b9feb.firebasestorage.app',
    iosBundleId: 'com.example.miAplicacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm4I8OVRulnkvS1t_iiOZyVGSzqb0KnZA',
    appId: '1:1098384504032:ios:1424ed2032770875f8cc85',
    messagingSenderId: '1098384504032',
    projectId: 'homs-b9feb',
    storageBucket: 'homs-b9feb.firebasestorage.app',
    iosBundleId: 'com.example.miAplicacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpBeIVAmMvTOnYOKBR9sBMZmhqq3b4STg',
    appId: '1:1098384504032:web:8cb52a60cf1e9e2af8cc85',
    messagingSenderId: '1098384504032',
    projectId: 'homs-b9feb',
    authDomain: 'homs-b9feb.firebaseapp.com',
    storageBucket: 'homs-b9feb.firebasestorage.app',
    measurementId: 'G-0QZ3K4QLQZ',
  );
}
