// Mocks generated by Mockito 5.4.6 from annotations
// in happy_oven/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:happy_oven/core/models/alerta.dart' as _i6;
import 'package:happy_oven/core/models/articulo.dart' as _i2;
import 'package:happy_oven/core/models/categoria.dart' as _i7;
import 'package:happy_oven/core/models/enums.dart' as _i15;
import 'package:happy_oven/core/models/movimiento.dart' as _i5;
import 'package:happy_oven/core/models/orden_produccion.dart' as _i8;
import 'package:happy_oven/core/models/receta.dart' as _i3;
import 'package:happy_oven/core/models/receta_ingrediente.dart' as _i4;
import 'package:happy_oven/core/repositories/alertas_repository.dart' as _i18;
import 'package:happy_oven/core/repositories/articulos_repository.dart' as _i17;
import 'package:happy_oven/core/repositories/i_alertas_repository.dart' as _i13;
import 'package:happy_oven/core/repositories/i_articulos_repository.dart'
    as _i9;
import 'package:happy_oven/core/repositories/i_categorias_repository.dart'
    as _i14;
import 'package:happy_oven/core/repositories/i_movimientos_repository.dart'
    as _i12;
import 'package:happy_oven/core/repositories/i_ordenes_produccion_repository.dart'
    as _i16;
import 'package:happy_oven/core/repositories/i_recetas_repository.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeArticulo_0 extends _i1.SmartFake implements _i2.Articulo {
  _FakeArticulo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReceta_1 extends _i1.SmartFake implements _i3.Receta {
  _FakeReceta_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecetaIngrediente_2 extends _i1.SmartFake
    implements _i4.RecetaIngrediente {
  _FakeRecetaIngrediente_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovimiento_3 extends _i1.SmartFake implements _i5.Movimiento {
  _FakeMovimiento_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAlerta_4 extends _i1.SmartFake implements _i6.Alerta {
  _FakeAlerta_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoria_5 extends _i1.SmartFake implements _i7.Categoria {
  _FakeCategoria_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrdenProduccion_6 extends _i1.SmartFake
    implements _i8.OrdenProduccion {
  _FakeOrdenProduccion_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IArticulosRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIArticulosRepository extends _i1.Mock
    implements _i9.IArticulosRepository {
  MockIArticulosRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i2.Articulo>> getArticulos() =>
      (super.noSuchMethod(
            Invocation.method(#getArticulos, []),
            returnValue: _i10.Future<List<_i2.Articulo>>.value(
              <_i2.Articulo>[],
            ),
          )
          as _i10.Future<List<_i2.Articulo>>);

  @override
  _i10.Future<List<_i2.Articulo>> getInsumos() =>
      (super.noSuchMethod(
            Invocation.method(#getInsumos, []),
            returnValue: _i10.Future<List<_i2.Articulo>>.value(
              <_i2.Articulo>[],
            ),
          )
          as _i10.Future<List<_i2.Articulo>>);

  @override
  _i10.Future<List<_i2.Articulo>> getProductosFinales() =>
      (super.noSuchMethod(
            Invocation.method(#getProductosFinales, []),
            returnValue: _i10.Future<List<_i2.Articulo>>.value(
              <_i2.Articulo>[],
            ),
          )
          as _i10.Future<List<_i2.Articulo>>);

  @override
  _i10.Future<_i2.Articulo?> getArticuloById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getArticuloById, [id]),
            returnValue: _i10.Future<_i2.Articulo?>.value(),
          )
          as _i10.Future<_i2.Articulo?>);

  @override
  _i10.Future<_i2.Articulo> createArticulo(_i2.Articulo? articulo) =>
      (super.noSuchMethod(
            Invocation.method(#createArticulo, [articulo]),
            returnValue: _i10.Future<_i2.Articulo>.value(
              _FakeArticulo_0(
                this,
                Invocation.method(#createArticulo, [articulo]),
              ),
            ),
          )
          as _i10.Future<_i2.Articulo>);

  @override
  _i10.Future<_i2.Articulo> updateArticulo(_i2.Articulo? articulo) =>
      (super.noSuchMethod(
            Invocation.method(#updateArticulo, [articulo]),
            returnValue: _i10.Future<_i2.Articulo>.value(
              _FakeArticulo_0(
                this,
                Invocation.method(#updateArticulo, [articulo]),
              ),
            ),
          )
          as _i10.Future<_i2.Articulo>);

  @override
  _i10.Future<void> deleteArticulo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteArticulo, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [IRecetasRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRecetasRepository extends _i1.Mock
    implements _i11.IRecetasRepository {
  MockIRecetasRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i3.Receta>> getRecetas() =>
      (super.noSuchMethod(
            Invocation.method(#getRecetas, []),
            returnValue: _i10.Future<List<_i3.Receta>>.value(<_i3.Receta>[]),
          )
          as _i10.Future<List<_i3.Receta>>);

  @override
  _i10.Future<_i3.Receta?> getRecetaById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRecetaById, [id]),
            returnValue: _i10.Future<_i3.Receta?>.value(),
          )
          as _i10.Future<_i3.Receta?>);

  @override
  _i10.Future<_i3.Receta?> getRecetaByProductoId(String? productoId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecetaByProductoId, [productoId]),
            returnValue: _i10.Future<_i3.Receta?>.value(),
          )
          as _i10.Future<_i3.Receta?>);

  @override
  _i10.Future<_i3.Receta> createReceta(_i3.Receta? receta) =>
      (super.noSuchMethod(
            Invocation.method(#createReceta, [receta]),
            returnValue: _i10.Future<_i3.Receta>.value(
              _FakeReceta_1(this, Invocation.method(#createReceta, [receta])),
            ),
          )
          as _i10.Future<_i3.Receta>);

  @override
  _i10.Future<_i3.Receta> updateReceta(_i3.Receta? receta) =>
      (super.noSuchMethod(
            Invocation.method(#updateReceta, [receta]),
            returnValue: _i10.Future<_i3.Receta>.value(
              _FakeReceta_1(this, Invocation.method(#updateReceta, [receta])),
            ),
          )
          as _i10.Future<_i3.Receta>);

  @override
  _i10.Future<void> deleteReceta(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReceta, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i4.RecetaIngrediente>> getIngredientesPorReceta(
    String? recetaId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getIngredientesPorReceta, [recetaId]),
            returnValue: _i10.Future<List<_i4.RecetaIngrediente>>.value(
              <_i4.RecetaIngrediente>[],
            ),
          )
          as _i10.Future<List<_i4.RecetaIngrediente>>);

  @override
  _i10.Future<_i4.RecetaIngrediente> addIngrediente(
    _i4.RecetaIngrediente? ingrediente,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addIngrediente, [ingrediente]),
            returnValue: _i10.Future<_i4.RecetaIngrediente>.value(
              _FakeRecetaIngrediente_2(
                this,
                Invocation.method(#addIngrediente, [ingrediente]),
              ),
            ),
          )
          as _i10.Future<_i4.RecetaIngrediente>);

  @override
  _i10.Future<void> deleteIngrediente(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteIngrediente, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i4.RecetaIngrediente>> reemplazarIngredientes(
    String? recetaId,
    List<_i4.RecetaIngrediente>? ingredientes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reemplazarIngredientes, [
              recetaId,
              ingredientes,
            ]),
            returnValue: _i10.Future<List<_i4.RecetaIngrediente>>.value(
              <_i4.RecetaIngrediente>[],
            ),
          )
          as _i10.Future<List<_i4.RecetaIngrediente>>);
}

/// A class which mocks [IMovimientosRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMovimientosRepository extends _i1.Mock
    implements _i12.IMovimientosRepository {
  MockIMovimientosRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i5.Movimiento>> getHistorialMovimientos() =>
      (super.noSuchMethod(
            Invocation.method(#getHistorialMovimientos, []),
            returnValue: _i10.Future<List<_i5.Movimiento>>.value(
              <_i5.Movimiento>[],
            ),
          )
          as _i10.Future<List<_i5.Movimiento>>);

  @override
  _i10.Future<List<_i5.Movimiento>> getMovimientosPorArticulo(
    String? articuloId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovimientosPorArticulo, [articuloId]),
            returnValue: _i10.Future<List<_i5.Movimiento>>.value(
              <_i5.Movimiento>[],
            ),
          )
          as _i10.Future<List<_i5.Movimiento>>);

  @override
  _i10.Future<_i5.Movimiento> registrarMovimiento(_i5.Movimiento? movimiento) =>
      (super.noSuchMethod(
            Invocation.method(#registrarMovimiento, [movimiento]),
            returnValue: _i10.Future<_i5.Movimiento>.value(
              _FakeMovimiento_3(
                this,
                Invocation.method(#registrarMovimiento, [movimiento]),
              ),
            ),
          )
          as _i10.Future<_i5.Movimiento>);

  @override
  _i10.Future<void> deleteMovimiento(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMovimiento, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i5.Movimiento>> getMovimientosPorRango(
    DateTime? inicio,
    DateTime? fin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovimientosPorRango, [inicio, fin]),
            returnValue: _i10.Future<List<_i5.Movimiento>>.value(
              <_i5.Movimiento>[],
            ),
          )
          as _i10.Future<List<_i5.Movimiento>>);
}

/// A class which mocks [IAlertasRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAlertasRepository extends _i1.Mock
    implements _i13.IAlertasRepository {
  MockIAlertasRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i6.Alerta>> getAlertasPendientes() =>
      (super.noSuchMethod(
            Invocation.method(#getAlertasPendientes, []),
            returnValue: _i10.Future<List<_i6.Alerta>>.value(<_i6.Alerta>[]),
          )
          as _i10.Future<List<_i6.Alerta>>);

  @override
  _i10.Future<List<_i6.Alerta>> getHistorialAlertas() =>
      (super.noSuchMethod(
            Invocation.method(#getHistorialAlertas, []),
            returnValue: _i10.Future<List<_i6.Alerta>>.value(<_i6.Alerta>[]),
          )
          as _i10.Future<List<_i6.Alerta>>);

  @override
  _i10.Future<_i6.Alerta> createAlerta(_i6.Alerta? alerta) =>
      (super.noSuchMethod(
            Invocation.method(#createAlerta, [alerta]),
            returnValue: _i10.Future<_i6.Alerta>.value(
              _FakeAlerta_4(this, Invocation.method(#createAlerta, [alerta])),
            ),
          )
          as _i10.Future<_i6.Alerta>);

  @override
  _i10.Future<void> marcarComoLeida(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#marcarComoLeida, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> marcarTodasComoLeidas() =>
      (super.noSuchMethod(
            Invocation.method(#marcarTodasComoLeidas, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteAlerta(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAlerta, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [ICategoriasRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockICategoriasRepository extends _i1.Mock
    implements _i14.ICategoriasRepository {
  MockICategoriasRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i7.Categoria>> getCategorias() =>
      (super.noSuchMethod(
            Invocation.method(#getCategorias, []),
            returnValue: _i10.Future<List<_i7.Categoria>>.value(
              <_i7.Categoria>[],
            ),
          )
          as _i10.Future<List<_i7.Categoria>>);

  @override
  _i10.Future<List<_i7.Categoria>> getCategoriasPorTipo(
    _i15.TipoArticulo? tipo,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoriasPorTipo, [tipo]),
            returnValue: _i10.Future<List<_i7.Categoria>>.value(
              <_i7.Categoria>[],
            ),
          )
          as _i10.Future<List<_i7.Categoria>>);

  @override
  _i10.Future<_i7.Categoria> createCategoria(_i7.Categoria? categoria) =>
      (super.noSuchMethod(
            Invocation.method(#createCategoria, [categoria]),
            returnValue: _i10.Future<_i7.Categoria>.value(
              _FakeCategoria_5(
                this,
                Invocation.method(#createCategoria, [categoria]),
              ),
            ),
          )
          as _i10.Future<_i7.Categoria>);

  @override
  _i10.Future<_i7.Categoria> updateCategoria(_i7.Categoria? categoria) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategoria, [categoria]),
            returnValue: _i10.Future<_i7.Categoria>.value(
              _FakeCategoria_5(
                this,
                Invocation.method(#updateCategoria, [categoria]),
              ),
            ),
          )
          as _i10.Future<_i7.Categoria>);

  @override
  _i10.Future<void> deleteCategoria(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategoria, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [IOrdenesProduccionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOrdenesProduccionRepository extends _i1.Mock
    implements _i16.IOrdenesProduccionRepository {
  MockIOrdenesProduccionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i8.OrdenProduccion>> getOrdenes() =>
      (super.noSuchMethod(
            Invocation.method(#getOrdenes, []),
            returnValue: _i10.Future<List<_i8.OrdenProduccion>>.value(
              <_i8.OrdenProduccion>[],
            ),
          )
          as _i10.Future<List<_i8.OrdenProduccion>>);

  @override
  _i10.Future<List<_i8.OrdenProduccion>> getOrdenesPorEstado(String? estado) =>
      (super.noSuchMethod(
            Invocation.method(#getOrdenesPorEstado, [estado]),
            returnValue: _i10.Future<List<_i8.OrdenProduccion>>.value(
              <_i8.OrdenProduccion>[],
            ),
          )
          as _i10.Future<List<_i8.OrdenProduccion>>);

  @override
  _i10.Future<_i8.OrdenProduccion?> getOrdenById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getOrdenById, [id]),
            returnValue: _i10.Future<_i8.OrdenProduccion?>.value(),
          )
          as _i10.Future<_i8.OrdenProduccion?>);

  @override
  _i10.Future<_i8.OrdenProduccion> createOrden(_i8.OrdenProduccion? orden) =>
      (super.noSuchMethod(
            Invocation.method(#createOrden, [orden]),
            returnValue: _i10.Future<_i8.OrdenProduccion>.value(
              _FakeOrdenProduccion_6(
                this,
                Invocation.method(#createOrden, [orden]),
              ),
            ),
          )
          as _i10.Future<_i8.OrdenProduccion>);

  @override
  _i10.Future<_i8.OrdenProduccion> updateOrden(_i8.OrdenProduccion? orden) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrden, [orden]),
            returnValue: _i10.Future<_i8.OrdenProduccion>.value(
              _FakeOrdenProduccion_6(
                this,
                Invocation.method(#updateOrden, [orden]),
              ),
            ),
          )
          as _i10.Future<_i8.OrdenProduccion>);

  @override
  _i10.Future<void> deleteOrden(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrden, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [ArticulosRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticulosRepository extends _i1.Mock
    implements _i17.ArticulosRepository {
  MockArticulosRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i2.Articulo>> getArticulos() =>
      (super.noSuchMethod(
            Invocation.method(#getArticulos, []),
            returnValue: _i10.Future<List<_i2.Articulo>>.value(
              <_i2.Articulo>[],
            ),
          )
          as _i10.Future<List<_i2.Articulo>>);

  @override
  _i10.Future<List<_i2.Articulo>> getInsumos() =>
      (super.noSuchMethod(
            Invocation.method(#getInsumos, []),
            returnValue: _i10.Future<List<_i2.Articulo>>.value(
              <_i2.Articulo>[],
            ),
          )
          as _i10.Future<List<_i2.Articulo>>);

  @override
  _i10.Future<List<_i2.Articulo>> getProductosFinales() =>
      (super.noSuchMethod(
            Invocation.method(#getProductosFinales, []),
            returnValue: _i10.Future<List<_i2.Articulo>>.value(
              <_i2.Articulo>[],
            ),
          )
          as _i10.Future<List<_i2.Articulo>>);

  @override
  _i10.Future<_i2.Articulo?> getArticuloById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getArticuloById, [id]),
            returnValue: _i10.Future<_i2.Articulo?>.value(),
          )
          as _i10.Future<_i2.Articulo?>);

  @override
  _i10.Future<_i2.Articulo> createArticulo(_i2.Articulo? articulo) =>
      (super.noSuchMethod(
            Invocation.method(#createArticulo, [articulo]),
            returnValue: _i10.Future<_i2.Articulo>.value(
              _FakeArticulo_0(
                this,
                Invocation.method(#createArticulo, [articulo]),
              ),
            ),
          )
          as _i10.Future<_i2.Articulo>);

  @override
  _i10.Future<_i2.Articulo> updateArticulo(_i2.Articulo? articulo) =>
      (super.noSuchMethod(
            Invocation.method(#updateArticulo, [articulo]),
            returnValue: _i10.Future<_i2.Articulo>.value(
              _FakeArticulo_0(
                this,
                Invocation.method(#updateArticulo, [articulo]),
              ),
            ),
          )
          as _i10.Future<_i2.Articulo>);

  @override
  _i10.Future<void> deleteArticulo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteArticulo, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [AlertasRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlertasRepository extends _i1.Mock implements _i18.AlertasRepository {
  MockAlertasRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i6.Alerta>> getAlertasPendientes() =>
      (super.noSuchMethod(
            Invocation.method(#getAlertasPendientes, []),
            returnValue: _i10.Future<List<_i6.Alerta>>.value(<_i6.Alerta>[]),
          )
          as _i10.Future<List<_i6.Alerta>>);

  @override
  _i10.Future<List<_i6.Alerta>> getHistorialAlertas() =>
      (super.noSuchMethod(
            Invocation.method(#getHistorialAlertas, []),
            returnValue: _i10.Future<List<_i6.Alerta>>.value(<_i6.Alerta>[]),
          )
          as _i10.Future<List<_i6.Alerta>>);

  @override
  _i10.Future<_i6.Alerta> createAlerta(_i6.Alerta? alerta) =>
      (super.noSuchMethod(
            Invocation.method(#createAlerta, [alerta]),
            returnValue: _i10.Future<_i6.Alerta>.value(
              _FakeAlerta_4(this, Invocation.method(#createAlerta, [alerta])),
            ),
          )
          as _i10.Future<_i6.Alerta>);

  @override
  _i10.Future<void> marcarComoLeida(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#marcarComoLeida, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> marcarTodasComoLeidas() =>
      (super.noSuchMethod(
            Invocation.method(#marcarTodasComoLeidas, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteAlerta(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAlerta, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}
